// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOuOK4baRd-awrRLNs7hxgktO7C9wedJ0',
    appId: '1:819200068744:web:913715586403acf52c633d',
    messagingSenderId: '819200068744',
    projectId: 'calendar-scheduler-10',
    authDomain: 'calendar-scheduler-10.firebaseapp.com',
    storageBucket: 'calendar-scheduler-10.firebasestorage.app',
    measurementId: 'G-F5TN629KLY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7_uiiQhz2zox1trHM2yW2L2zTXMpqGpo',
    appId: '1:819200068744:android:7c2dbcc41bffb69c2c633d',
    messagingSenderId: '819200068744',
    projectId: 'calendar-scheduler-10',
    storageBucket: 'calendar-scheduler-10.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsmVsBZyh8tPWAFjkmkfgg1RGDv-qZz2s',
    appId: '1:819200068744:ios:8f74a1fce65f6c552c633d',
    messagingSenderId: '819200068744',
    projectId: 'calendar-scheduler-10',
    storageBucket: 'calendar-scheduler-10.firebasestorage.app',
    iosBundleId: 'com.example.flutterCalendarScheduler',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsmVsBZyh8tPWAFjkmkfgg1RGDv-qZz2s',
    appId: '1:819200068744:ios:8f74a1fce65f6c552c633d',
    messagingSenderId: '819200068744',
    projectId: 'calendar-scheduler-10',
    storageBucket: 'calendar-scheduler-10.firebasestorage.app',
    iosBundleId: 'com.example.flutterCalendarScheduler',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOuOK4baRd-awrRLNs7hxgktO7C9wedJ0',
    appId: '1:819200068744:web:b344a9ceda1f1f432c633d',
    messagingSenderId: '819200068744',
    projectId: 'calendar-scheduler-10',
    authDomain: 'calendar-scheduler-10.firebaseapp.com',
    storageBucket: 'calendar-scheduler-10.firebasestorage.app',
    measurementId: 'G-Q5EFVS474Z',
  );
}
